import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "../components/layoutWrapper";
import Providers from "../components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by CH Arham",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Small inline script to set initial theme class before React hydrates to prevent
  // hydration mismatches from next-themes updating document.documentElement.className
  const setInitialTheme = `(() => {
    try {
      const theme = localStorage.getItem('theme');
      const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
      if (theme === 'dark' || (!theme && prefersDark)) {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    } catch (e) {}
  })()`;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {setInitialTheme}
        </Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased min-h-screen w-screen overflow-x-hidden`}>
         <Providers>
           <LayoutWrapper>
             {children}
           </LayoutWrapper>
         </Providers>
       </body>
     </html>
   );
 }
